@PACKAGE_INIT@
include(CMakeFindDependencyMacro)

set(LIBDWARF_BUILT_WITH_ZLIB_AND_ZSTD "@BUILT_WITH_ZLIB_AND_ZSTD@")

if(LIBDWARF_BUILT_WITH_ZLIB_AND_ZSTD)
  find_dependency(ZLIB)
  set(CMAKE_MODULE_PATH_OLD "${CMAKE_MODULE_PATH}")
  set(CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH};${CMAKE_CURRENT_LIST_DIR}")
  find_dependency(zstd)
  set(CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH_OLD}")
  unset(CMAKE_MODULE_PATH_OLD)
endif()

if(NOT TARGET libdwarf::dwarf)
  include(${CMAKE_CURRENT_LIST_DIR}/libdwarf-targets.cmake)
  if(DEFINED LIBDWARF_USE_STATIC_LIBS)
    set(_use_static "${LIBDWARF_USE_STATIC_LIBS}")
  elseif(DEFINED BUILD_SHARED_LIBS)
    if(BUILD_SHARED_LIBS)
      set(_use_static OFF)
    else()
      set(_use_static ON)
    endif()
  else()
    set(_use_static OFF)
  endif()
  if(_use_static)
    add_library(libdwarf::dwarf ALIAS libdwarf::dwarf-static)
  else()
    add_library(libdwarf::dwarf ALIAS libdwarf::dwarf-shared)
  endif()

  check_required_components(libdwarf)
endif()
