@PACKAGE_INIT@
include(CMakeFindDependencyMacro)

if(NOT TARGET libdwarfp::libdwarfp)
  include(${CMAKE_CURRENT_LIST_DIR}/libdwarfp-targets.cmake)
  if(DEFINED LIBDWARF_USE_STATIC_LIBS)
    set(_use_static "${LIBDWARF_USE_STATIC_LIBS}")
  elseif(DEFINED BUILD_SHARED_LIBS)
    if(BUILD_SHARED_LIBS)
      set(_use_static OFF)
    else()
      set(_use_static ON)
    endif()
  else()
    set(_use_static OFF)
  endif()
  if(_use_static)
    add_library(libdwarf::dwarfp ALIAS libdwarf::dwarfp-static)
  else()
    add_library(libdwarf::dwarfp ALIAS libdwarf::dwarfp-shared)
  endif()

  check_required_components(libdwarfp)
endif()